version: '3.8'
services:
    domain:
        container_name: domain
        build:
            context: ./docker/domain
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./www/domain:/var/www/html/
        ports:
            - 801:80
    sub_domain:
        container_name: sub_domain
        build:
            context: ./docker/sub_domain
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./www/sub_domain:/var/www/html/
        ports:
            - 802:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: __MYSQL_ROOT_PASSWORD__
            MYSQL_DATABASE: __MYSQL_DATABASE__
            MYSQL_USER: __MYSQL_USER__
            MYSQL_PASSWORD: __MYSQL_PASSWORD__
        ports:
            - "9906:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db